site:
  title: Документация Quality Solution
  url: http://doc.qsolution.ru
  start_page: workwear::introduction.adoc

content:
  edit_url: ~
  sources: 
  - url: ../Workwear/
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/qualitysolution-public/antora-ui-default-russian/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ru]
